### ISSUE TITLE
nuget 5.2.1 Warning CS8032

### ISSUE THREAD

**Issue by denhaandrei** [security-code-scan/security-code-scan#218]
**Environment:**
 - Version: 5.2.1
 - Branch:
   - [x] vs2019 
   - [ ] vs2017 
   - [ ] vs2015 
 - Installation/Running method:
   - [ ] Visual Studio Extension 
   - [x] NuGet package
   - [ ] Standalone tool
     - [ ] DotNet Core Tool from NuGet
     - [ ] security-scan4x.zip from GitHub Release section
 - Operating System:
   - [x] Windows
   - [ ] Linux
   - [ ] Mac
 - VS version:
 Microsoft Visual Studio Enterprise 2019 - Version 16.10.4

**Describe the bug**
Warning	CS8032	An instance of analyzer SecurityCodeScan.Analyzers.AthorizationAttributeDiagnosticAnalyzer cannot be created from &\securitycodescan.vs2019\5.2.1\analyzers\dotnet\SecurityCodeScan.VS2019.dll: Exception has been thrown by the target of an invocation..	

**Error Stack trace**
Warning	CS8032	An instance of analyzer SecurityCodeScan.Analyzers.CompilationAnalyzer cannot be created from **\.nuget\packages\securitycodescan.vs2019\5.2.1\analyzers\dotnet\SecurityCodeScan.VS2019.dll: Exception has been thrown by the target of an invocation, System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'SecurityCodeScan.Analyzers.CompilationAnalyzer' threw an exception. ---> System.MissingMethodException: Method not found: 'YamlDotNet.Helpers.IOrderedDictionary`2<YamlDotNet.RepresentationModel.YamlNode,YamlDotNet.RepresentationModel.YamlNode> YamlDotNet.RepresentationModel.YamlMappingNode.get_Children()'.
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager..ctor()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.get_ResourceManager()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.CompilationAnalyzer..cctor()
   --- End of inner exception stack trace ---
   at SecurityCodeScan.Analyzers.CompilationAnalyzer..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference.Extensions`1.GetAnalyzersForTypeNames(Assembly analyzerAssembly, IEnumerable`1 analyzerTypeNames, Boolean& reportedError)
-----
System.TypeInitializationException: The type initializer for 'SecurityCodeScan.Analyzers.CompilationAnalyzer' threw an exception. ---> System.MissingMethodException: Method not found: 'YamlDotNet.Helpers.IOrderedDictionary`2<YamlDotNet.RepresentationModel.YamlNode,YamlDotNet.RepresentationModel.YamlNode> YamlDotNet.RepresentationModel.YamlMappingNode.get_Children()'.
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager..ctor()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.get_ResourceManager()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.CompilationAnalyzer..cctor()
   --- End of inner exception stack trace ---
   at SecurityCodeScan.Analyzers.CompilationAnalyzer..ctor()
-----
System.MissingMethodException: Method not found: 'YamlDotNet.Helpers.IOrderedDictionary`2<YamlDotNet.RepresentationModel.YamlNode,YamlDotNet.RepresentationModel.YamlNode> YamlDotNet.RepresentationModel.YamlMappingNode.get_Children()'.
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager..ctor()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.get_ResourceManager()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.CompilationAnalyzer..cctor()
-----

**Repro**
not secure

**Comment by tillig** [comment]
Possible duplicate #200

**Comment by JarLob** [comment]
I would rather say of #208 but there is no repro scenario provided.

**Comment by Plasma** [comment]
I'm seeing this in my main project, and a very simple Hello World. The warning appears to only show up in VS, a build from the CLI shows no problems.

Please find attached a repo case, if you open and build in VS, on the Errors pane you will see (similar) MissingMethod warnings.
[CscWarningRepo.zip](https://github.com/security-code-scan/security-code-scan/files/6989171/CscWarningRepo.zip)

**Comment by JarLob** [comment]
Sorry it took me so long to look at the attached project. Unfortunately I cannot reproduce.
Some thoughts why:
1. If this is really dup of #208 I think the latest VS has implemented analyzers isolation. My VS version to the date is 16.11.3. Could you try to verify you have the latest version and still can reproduce it?
2. Not sure, but maybe the cause is wrong [configuration file](https://security-code-scan.github.io/#ExternalConfigurationFiles) Could you please check you don't have one?

**Comment by ForNeVeR** [comment]
FYI, we still observe a lot of such issues in Rider's Roslyn support as well. We have no information on which analyzer versions the users use, though. But the reports keep coming. Initially I thought it was just a Rider issue, but now when I see a similar report from a VS user, I'm not sure.

**Comment by denhaandrei** [comment]
VS 16.11.7 the same error:

Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	CS8032	An instance of analyzer SecurityCodeScan.Analyzers.XsltSettingsAnalyzer cannot be created from E:\GitClaimPortal\packages\SecurityCodeScan.VS2019.5.2.1\analyzers\dotnet\SecurityCodeScan.VS2019.dll: Exception has been thrown by the target of an invocation..	HHS.Claims.Portal		1	Active	System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'SecurityCodeScan.Analyzers.XsltSettingsAnalyzer' threw an exception. ---> System.MissingMethodException: Method not found: 'YamlDotNet.Helpers.IOrderedDictionary`2<YamlDotNet.RepresentationModel.YamlNode,YamlDotNet.RepresentationModel.YamlNode> YamlDotNet.RepresentationModel.YamlMappingNode.get_Children()'.
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager..ctor()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.get_ResourceManager()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.XsltSettingsAnalyzer..cctor()
   --- End of inner exception stack trace ---
   at SecurityCodeScan.Analyzers.XsltSettingsAnalyzer..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference.Extensions`1.GetAnalyzersForTypeNames(Assembly analyzerAssembly, IEnumerable`1 analyzerTypeNames, Boolean& reportedError)
-----
System.TypeInitializationException: The type initializer for 'SecurityCodeScan.Analyzers.XsltSettingsAnalyzer' threw an exception. ---> System.MissingMethodException: Method not found: 'YamlDotNet.Helpers.IOrderedDictionary`2<YamlDotNet.RepresentationModel.YamlNode,YamlDotNet.RepresentationModel.YamlNode> YamlDotNet.RepresentationModel.YamlMappingNode.get_Children()'.
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager..ctor()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.get_ResourceManager()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.XsltSettingsAnalyzer..cctor()
   --- End of inner exception stack trace ---
   at SecurityCodeScan.Analyzers.XsltSettingsAnalyzer..ctor()
-----
System.MissingMethodException: Method not found: 'YamlDotNet.Helpers.IOrderedDictionary`2<YamlDotNet.RepresentationModel.YamlNode,YamlDotNet.RepresentationModel.YamlNode> YamlDotNet.RepresentationModel.YamlMappingNode.get_Children()'.
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager..ctor()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.get_ResourceManager()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.XsltSettingsAnalyzer..cctor()
-----
