### ISSUE TITLE
Standalone scanner throws exception: 'ProjectName' is already part of the workspace

### ISSUE THREAD

**Issue by bozonas** [security-code-scan/security-code-scan#258]
**Environment:**
 - Version: 5.6.5
 - Installation/Running method:
   - [ ] Visual Studio Extension 
   - [ ] NuGet package
   - [x] Standalone tool
     - [x] DotNet Core Tool from NuGet
     - [ ] security-scan4x.zip from GitHub Release section
 - Operating System:
   - [x] Windows
   - [x] Linux
   - [ ] Mac

**Describe the bug**
Standalone scanner throws exception with newest version v5.6.5. Everything works fine with v5.6.3.

```
dotnet tool install --global security-scan
security-scan $(solution)
```
Output:
```
❯ security-scan payment.sln

╔═╗┌─┐┌─┐┬ ┬┬─┐┬┌┬┐┬ ┬  ╔═╗┌─┐┌┬┐┌─┐  ╔═╗┌─┐┌─┐┌┐┌
╚═╗├┤ │  │ │├┬┘│ │ └┬┘  ║  │ │ ││├┤   ╚═╗│  ├─┤│││
╚═╝└─┘└─┘└─┘┴└─┴ ┴  ┴   ╚═╝└─┘─┴┘└─┘  ╚═╝└─┘┴ ┴┘└┘

.NET tool by Jaroslav Lobačevski v5.6.5


Loading solution '[removed].sln'
Resolve         0:00.0171850    Application.csproj (net6.0)
Resolve         0:00.0120746    Infrastructure.csproj (net6.0)
Resolve         0:00.5166888    WebApi.csproj (net6.0)
Unhandled exception. System.ArgumentException: 'Application' is already part of the workspace.
   at Microsoft.CodeAnalysis.Workspace.CheckProjectIsNotInCurrentSolution(ProjectId projectId)
   at Microsoft.CodeAnalysis.Workspace.OnProjectAdded_NoLock(ProjectInfo projectInfo, Boolean silent)
   at Microsoft.CodeAnalysis.Workspace.OnProjectAdded(ProjectInfo projectInfo, Boolean silent)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.OpenProjectAsync(String projectFilePath, ILogger msbuildLogger, IProgress`1 progress, CancellationToken cancellationToken)
   at SecurityCodeScan.Tool.Program.Main(String[] args) in D:\a\security-code-scan\security-code-scan\SecurityCodeScan.Tool\Program.cs:line 378
   at SecurityCodeScan.Tool.Program.<Main>(String[] args)
```

**Comment by JarLob** [comment]
Thank you for reporting, do you have a reproducible solution?

**Comment by bozonas** [comment]
Sorry, I can't share the solution

**Comment by MarcelMichau** [comment]
Hello all!

I have a solution for repro which exhibits this issue: https://github.com/MarcelMichau/fake-survey-generator

The Docker Compose project just needs to be excluded from the scan, so this is the command I ran:

```
security-scan .\FakeSurveyGenerator.sln --excl-proj "**/*.dcproj"
```

This results in the following output:

```
security-scan .\FakeSurveyGenerator.sln --excl-proj "**/*.dcproj"

╔═╗┌─┐┌─┐┬ ┬┬─┐┬┌┬┐┬ ┬  ╔═╗┌─┐┌┬┐┌─┐  ╔═╗┌─┐┌─┐┌┐┌
╚═╗├┤ │  │ │├┬┘│ │ └┬┘  ║  │ │ ││├┤   ╚═╗│  ├─┤│││
╚═╝└─┘└─┘└─┘┴└─┴ ┴  ┴   ╚═╝└─┘─┴┘└─┘  ╚═╝└─┘┴ ┴┘└┘

.NET tool by Jaroslav Lobačevski v5.6.5


Loading solution '.\FakeSurveyGenerator.sln'
Skipped: C:\Source\fake-survey-generator\docker-compose.dcproj excluded from analysis
Resolve         0:00.0393958    FakeSurveyGenerator.Shared.csproj (net6.0)
Resolve         0:00.4916011    FakeSurveyGenerator.Domain.csproj (net6.0)
Resolve         0:00.0312366    FakeSurveyGenerator.Application.csproj (net6.0)
Resolve         0:00.5791649    FakeSurveyGenerator.Infrastructure.csproj (net6.0)
Resolve         0:02.7152933    FakeSurveyGenerator.API.csproj (net6.0)
Resolve         0:00.0444785    FakeSurveyGenerator.Data.csproj (net6.0)
Resolve         0:00.7048754    FakeSurveyGenerator.API.Tests.Integration.csproj (net6.0)
Unhandled exception. System.ArgumentException: 'FakeSurveyGenerator.Domain' is already part of the workspace.
   at Microsoft.CodeAnalysis.Workspace.CheckProjectIsNotInCurrentSolution(ProjectId projectId)
   at Microsoft.CodeAnalysis.Workspace.OnProjectAdded_NoLock(ProjectInfo projectInfo, Boolean silent)
   at Microsoft.CodeAnalysis.Workspace.OnProjectAdded(ProjectInfo projectInfo, Boolean silent)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.OpenProjectAsync(String projectFilePath, ILogger msbuildLogger, IProgress`1 progress, CancellationToken cancellationToken)
   at SecurityCodeScan.Tool.Program.Main(String[] args) in D:\a\security-code-scan\security-code-scan\SecurityCodeScan.Tool\Program.cs:line 378
   at SecurityCodeScan.Tool.Program.<Main>(String[] args)
```

**Comment by mysterio2465** [comment]
Just as an fyi, this worked in 5.6.3. May have been introduced in either 5.6.4 or 5.6.5 not exactly sure as the Solution Items issue may have obscured this issue for me.
