### ISSUE TITLE
New exceptions thrown for SCS extension after upgrading VS

### ISSUE THREAD

**Issue by catherinelpowell** [security-code-scan/security-code-scan#289]
**Environment:**
 - Version: 5.6.7

 - Installation/Running method:
   - [x ] Visual Studio Extension  System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.Taint.LdapFilterTaintAnalyzer..cctor()
   --- End of inner exception stack trace ---
   at SecurityCodeScan.Analyzers.XxeDiagnosticAnalyzer.get_SupportedDiagnostics()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.<>c__DisplayClass21_0.<ComputeDiagnosticDescriptors_NoLock>b__0(Object _)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
-----
System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.Taint.LdapFilterTaintAnalyzer..cctor()
-----

Analyzer 'SecurityCodeScan.Analyzers.XxeDiagnosticAnalyzerVisualBasic' threw the following exception:
'System.TypeInitializationException: The type initializer for 'SecurityCodeScan.Analyzers.XxeDiagnosticAnalyzer' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.Taint.LdapFilterTaintAnalyzer..cctor()
   --- End of inner exception stack trace ---
   at SecurityCodeScan.Analyzers.XxeDiagnosticAnalyzer.get_SupportedDiagnostics()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.CreateDisablingMessage(DiagnosticAnalyzer analyzer, String analyzerName)
-----
System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.Taint.LdapFilterTaintAnalyzer..cctor()
-----
'.	1_App_Code	C:\Workspaces\W2G\W2G.sln	1	Active
Warning	AD0001	Analyzer 'SecurityCodeScan.Analyzers.Taint.DeserializationTaintAnalyzer' threw an exception of type 'System.TypeInitializationException' with message 'The type initializer for 'SecurityCodeScan.Analyzers.Taint.DeserializationTaintAnalyzer' threw an exception.'.
System.TypeInitializationException: The type initializer for 'SecurityCodeScan.Analyzers.Taint.DeserializationTaintAnalyzer' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.Taint.LdapFilterTaintAnalyzer..cctor()
   --- End of inner exception stack trace ---
   at SecurityCodeScan.Analyzers.Taint.DeserializationTaintAnalyzer.get_TaintedDataEnteringSinkDescriptor()
   at SecurityCodeScan.Analyzers.Taint.TaintAnalyzer.get_SupportedDiagnostics()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.<>c__DisplayClass21_0.<ComputeDiagnosticDescriptors_NoLock>b__0(Object _)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
-----
System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.Taint.LdapFilterTaintAnalyzer..cctor()
-----

Analyzer 'SecurityCodeScan.Analyzers.Taint.DeserializationTaintAnalyzer' threw the following exception:
'System.TypeInitializationException: The type initializer for 'SecurityCodeScan.Analyzers.Taint.DeserializationTaintAnalyzer' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.Taint.LdapFilterTaintAnalyzer..cctor()
   --- End of inner exception stack trace ---
   at SecurityCodeScan.Analyzers.Taint.DeserializationTaintAnalyzer.get_TaintedDataEnteringSinkDescriptor()
   at SecurityCodeScan.Analyzers.Taint.TaintAnalyzer.get_SupportedDiagnostics()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.CreateDisablingMessage(DiagnosticAnalyzer analyzer, String analyzerName)
-----
System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.Taint.LdapFilterTaintAnalyzer..cctor()
-----
'.	1_App_Code	C:\Workspaces\W2G\W2G.sln	1	Active
Warning	AD0001	Analyzer 'SecurityCodeScan.Analyzers.Taint.HardcodedPasswordAnalyzer' threw an exception of type 'System.TypeInitializationException' with message 'The type initializer for 'SecurityCodeScan.Analyzers.Taint.HardcodedPasswordAnalyzer' threw an exception.'.
System.TypeInitializationException: The type initializer for 'SecurityCodeScan.Analyzers.Taint.HardcodedPasswordAnalyzer' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.Taint.LdapFilterTaintAnalyzer..cctor()
   --- End of inner exception stack trace ---
   at SecurityCodeScan.Analyzers.Taint.HardcodedPasswordAnalyzer.get_TaintedDataEnteringSinkDescriptor()
   at SecurityCodeScan.Analyzers.Taint.ConstAnalyzer.get_SupportedDiagnostics()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.<>c__DisplayClass21_0.<ComputeDiagnosticDescriptors_NoLock>b__0(Object _)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
-----
System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.Taint.LdapFilterTaintAnalyzer..cctor()
-----

Analyzer 'SecurityCodeScan.Analyzers.Taint.HardcodedPasswordAnalyzer' threw the following exception:
'System.TypeInitializationException: The type initializer for 'SecurityCodeScan.Analyzers.Taint.HardcodedPasswordAnalyzer' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.Taint.LdapFilterTaintAnalyzer..cctor()
   --- End of inner exception stack trace ---
   at SecurityCodeScan.Analyzers.Taint.HardcodedPasswordAnalyzer.get_TaintedDataEnteringSinkDescriptor()
   at SecurityCodeScan.Analyzers.Taint.ConstAnalyzer.get_SupportedDiagnostics()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.CreateDisablingMessage(DiagnosticAnalyzer analyzer, String analyzerName)
-----
System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.Taint.LdapFilterTaintAnalyzer..cctor()
-----
'.	1_App_Code	C:\Workspaces\W2G\W2G.sln	1	Active

**Comment by SoulSeekkor** [comment]
Having the same problem, for a while now the extension is unusable in VS 2022.  Running it against the solution outputs hundreds of warnings like the following:

Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'SecurityCodeScan.Analyzers.Taint.PathTraversalTaintAnalyzer' threw an exception of type 'System.TypeInitializationException' with message 'The type initializer for 'SecurityCodeScan.Analyzers.Taint.PathTraversalTaintAnalyzer' threw an exception.'.
System.TypeInitializationException: The type initializer for 'SecurityCodeScan.Analyzers.Taint.PathTraversalTaintAnalyzer' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.XxeDiagnosticAnalyzer..cctor()
   --- End of inner exception stack trace ---
   at SecurityCodeScan.Analyzers.Taint.PathTraversalTaintAnalyzer.get_TaintedDataEnteringSinkDescriptor()
   at SecurityCodeScan.Analyzers.Taint.TaintAnalyzer.get_SupportedDiagnostics()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.<>c__DisplayClass21_0.<ComputeDiagnosticDescriptors_NoLock>b__0(Object _)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
-----
System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.XxeDiagnosticAnalyzer..cctor()
-----

Analyzer 'SecurityCodeScan.Analyzers.Taint.PathTraversalTaintAnalyzer' threw an exception of type 'System.TypeInitializationException' with message 'The type initializer for 'SecurityCodeScan.Analyzers.Taint.PathTraversalTaintAnalyzer' threw an exception.'.
System.TypeInitializationException: The type initializer for 'SecurityCodeScan.Analyzers.Taint.PathTraversalTaintAnalyzer' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.XxeDiagnosticAnalyzer..cctor()
   --- End of inner exception stack trace ---
   at SecurityCodeScan.Analyzers.Taint.PathTraversalTaintAnalyzer.get_TaintedDataEnteringSinkDescriptor()
   at SecurityCodeScan.Analyzers.Taint.TaintAnalyzer.get_SupportedDiagnostics()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.CreateDisablingMessage(DiagnosticAnalyzer analyzer, String analyzerName)
-----
System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.XxeDiagnosticAnalyzer..cctor()
-----	NDM Connections (net48)	C:\Users\mewert\Documents\Visual Studio Projects\ND Manager\NDM Connections\NDM Connections.vbproj	1	Active

**Comment by heinrich-ulbricht** [comment]
Same issue here, Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.7.7

Getting lots of those:

```
Severity	Code	Description	Source	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'SecurityCodeScan.Analyzers.Taint.CommandInjectionTaintAnalyzer' threw an exception of type 'System.TypeInitializationException' with message 'The type initializer for 'SecurityCodeScan.Analyzers.Taint.CommandInjectionTaintAnalyzer' threw an exception.'.
System.TypeInitializationException: The type initializer for 'SecurityCodeScan.Analyzers.Taint.CommandInjectionTaintAnalyzer' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'. The system cannot find the file specified.
File name: 'YamlDotNet, Version=11.0.0.0, Culture=neutral, PublicKeyToken=ec19458f3c15af5e'
   at SecurityCodeScan.Analyzers.Locale.YamlResourceManager.Load()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetLocalString(String id)
   at SecurityCodeScan.Analyzers.Locale.LocaleUtil.GetDescriptor(String id, String titleId, String descriptionId, DiagnosticSeverity severity, Boolean isEnabledByDefault, String[] args)
   at SecurityCodeScan.Analyzers.XxeDiagnosticAnalyzer..cctor()
   --- End of inner exception stack trace ---
   at SecurityCodeScan.Analyzers.Taint.CommandInjectionTaintAnalyzer.get_TaintedDataEnteringSinkDescriptor()
   at SecurityCodeScan.Analyzers.Taint.TaintAnalyzer.get_SupportedDiagnostics()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.AnalyzerExecutionContext.<>c__DisplayClass21_0.<ComputeDiagnosticDescriptors_NoLock>b__0(Object _)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
```
