### ISSUE TITLE
Security Scan no longer running in AzureDevOps pipeline

### ISSUE THREAD

**Issue by Eric1243123** [security-code-scan/security-code-scan#300]
**Environment:**
 - Version: 5.6.7
 - Branch:
   - [X] vs2019 
   - [ ] vs2017 
   - [ ] vs2015 
 - Installation/Running method:
   - [ ] Visual Studio Extension 
   - [X] NuGet package
   - [ ] Standalone tool
     - [ ] DotNet Core Tool from NuGet
     - [ ] security-scan4x.zip from GitHub Release section
 - Operating System:
   - [X] Windows
   - [ ] Linux
   - [ ] Mac

**Describe the bug**
When trying to run the security-scan via an Azure DevOps pipeline, I was getting an error about not setting the sdk-path despite not having it in the command for years. After adding it, I started getting the following error:

Tool 'security-scan' was reinstalled with the stable version (version '5.6.7').

╔═╗┌─┐┌─┐┬ ┬┬─┐┬┌┬┐┬ ┬  ╔═╗┌─┐┌┬┐┌─┐  ╔═╗┌─┐┌─┐┌┐┌
╚═╗├┤ │  │ │├┬┘│ │ └┬┘  ║  │ │ ││├┤   ╚═╗│  ├─┤│││
╚═╝└─┘└─┘└─┘┴└─┴ ┴  ┴   ╚═╝└─┘─┴┘└─┘  ╚═╝└─┘┴ ┴┘└┘

.NET tool by Jaroslav Lobačevski v5.6.7

Loading solution 'D:\AzureDevOps\agent-2\_work\2\s/MyProject.sln'
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Microsoft.Build.Evaluation.ToolsetConfigurationReader..ctor(PropertyDictionary`1 environmentProperties, PropertyDictionary`1 globalProperties)
   at Microsoft.Build.Evaluation.ToolsetReader.ReadAllToolsets(Dictionary`2 toolsets, ToolsetRegistryReader registryReader, ToolsetConfigurationReader configurationReader, PropertyDictionary`1 environmentProperties, PropertyDictionary`1 globalProperties, ToolsetDefinitionLocations locations)
   at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection(ToolsetRegistryReader registryReader, ToolsetConfigurationReader configReader)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly, Boolean useAsynchronousLogging, Boolean reuseProjectRootElementCache)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, ToolsetDefinitionLocations toolsetDefinitionLocations)
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties)
   at Microsoft.CodeAnalysis.MSBuild.Build.ProjectBuildManager.StartBatchBuild(IDictionary`2 globalProperties)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.LoadAsync(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.LoadSolutionInfoAsync(String solutionFilePath, IProgress`1 progress, ILogger msbuildLogger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.OpenSolutionAsync(String solutionFilePath, ILogger msbuildLogger, IProgress`1 progress, CancellationToken cancellationToken)
   at SecurityCodeScan.Tool.Program.Main(String[] args) in D:\a\security-code-scan\security-code-scan\SecurityCodeScan.Tool\Program.cs:line 364
   at SecurityCodeScan.Tool.Program.<Main>(String[] args)
##[error]Cmd.exe exited with code '-532462766'.

This all started around the time I updated to .NET8 from .NET6

**Repro**
If possible please attach a Visual Studio project that reproduces the bug. Otherwise provide a code snippet or a screenshot.

**Comment by JosefTheGuyWhoIs** [comment]
Ran into this as well, .NET8

**Comment by cvocvo** [comment]
Also had this issue and took a run at fixing it by migrating the source to target .NET 8 + upgrading nuget packages.
https://github.com/security-code-scan/security-code-scan/pull/301

**Edit:** Ran into issues at runtime in our pipelines so I abandoned this PR.

**Comment by Eric1243123** [comment]
After switching over to https://github.com/dotnetarium/DotnetariumSCS, our problem has been fixed. Hopefully this can help with your issue too
