### ISSUE TITLE
Errors when using external configuration files

### ISSUE THREAD

**Issue by jwu-au** [security-code-scan/security-code-scan#74]
Hi,

By following the doc to specify an external configuration file with *CsrfProtectionAttributes*, but it throws branch of errors like below one:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp' threw an exception of type 'System.Exception' with message 'Unhandled exception while visiting method private static ActionResult RedirectParent(string redirectUrl, string queryString = null)	Drachma.Web	D:\Source\selz\drachma\src\Drachma.Web\CSC	1	Active
Warning	AD0001	Analyzer 'SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp' threw an exception of type 'System.Exception' with message 'Unhandled exception while visiting method public FrameViewAttribute(bool hasLayout = true, bool allowOnlyModal = false)	Drachma.Web	D:\Source\selz\drachma\src\Drachma.Web\CSC	1	Active
...
```
A `SecurityCodeScan.config.yml` is aded as `AdditionalFiles` in a `ASP.NET MVC` project using full .net framework `4.6.1`, and building under vs2017 15.7.5 .
```
CsrfProtectionAttributes:
  - HttpMethodsNameSpace: System.Web.Mvc
    Drachma.Web.Mvc.Filters.SelzAntiForgeryTokenAttribute
```

Not sure what step I'm missing or it is a bug, can you kindly point out?
Thank you.

**Comment by JarLob** [comment]
Your config lacks `AntiCsrfAttribute:` before the attribute name.

**Comment by jwu-au** [comment]
Hi JarLob,

It was my typo that, I tried to use below (copied from original config):
```
CsrfProtectionAttributes:
  - HttpMethodsNameSpace: System.Web.Mvc
    AntiCsrfAttribute: System.Web.Mvc.ValidateAntiForgeryTokenAttribute
```

It still throws *AD0001* erros.

**Comment by jlikens** [comment]
Confirmed that the above behavior is encountered when attempting to add custom CSRF configuration per the docs.

<pre>
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'SecurityCodeScan.Analyzers.MvcCsrfTokenAnalyzer' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: input.
</pre>

Also:

<pre>
Warning	AD0001	Analyzer 'SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp' threw an exception of type 'System.Exception' with message 'Unhandled exception while visiting method public virtual bool TestAction(string testInput)
Parameter name: input.
</pre>

**Comment by JarLob** [comment]
@jwu-au I didn't notice that you are using config as an additional file first. There is one more line missing as shown in documentation - version:
```yml
Version: 1.0
CsrfProtectionAttributes:
  - HttpMethodsNameSpace: System.Web.Mvc
    AntiCsrfAttribute: System.Web.Mvc.ValidateAntiForgeryTokenAttribute
```
You may need to **restart whole Visual Studio** because the config is cached in memory.
In case of user global config the entry is not needed, but the file itself should be named `config-1.0.yml` 
In the future the version will be incremented in case of any breaking configuration changes.

@jlikens Do you add it as an additional file too? Or it doesn't work for you as user config?

**Comment by jwu-au** [comment]
Hi @JarLob ,

I confirmed that the `Version: 1.0` line is the thing I was missing. It turns out working perfectly now. 

An extra question of the CSRF, I need to disable this check in API project, what's the proper way to config this?

Thank you.

**Comment by JarLob** [comment]
You can disable SCS0016 for entire project by editing the severity to None: https://security-code-scan.github.io/#Severity A ruleset will be created for the project.

**Comment by hillmarcus** [comment]
I wrote up the following for a new issue but it looks like it's been thoroughly covered over here. I'm going to past what I wrote up below for documentation sake though, and to hopefully help other googlers find this page.

---

The constructor for System.Version in the following line will throw an exception if `projectConfig.Version` is `null`. I'm not sure what part of my setup is causing that property to be `null` but it is not intuitive that that is the problem.

https://github.com/security-code-scan/security-code-scan/blob/7f6d6d8cd3ef2b06161718e1b67628bd1090a8df/SecurityCodeScan/Config/ConfigurationManager.cs#L77

The error message I get from VS is this:
```
Severity - Warning
Code - AD0001
Project - (Project Name)
Description - Analyzer 'SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: input'.
File - (blank)
Line - 1
Detail Description:
Analyzer 'SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp' threw the following exception:
'Exception occurred with following context:
Compilation: (Project Name)

System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at SecurityCodeScan.Config.ConfigurationReader.GetProjectConfiguration(ImmutableArray`1 additionalFiles, String& path)
   at SecurityCodeScan.Config.ConfigurationManager.GetUpdatedProjectConfiguration(ImmutableArray`1 additionalFiles)
   at SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp.<>c.<Initialize>b__0_0(CompilationStartAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteCompilationStartActions>b__35_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

There's also a second exception with a slightly different message, but otherwise the same:

```
Analyzer 'SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp' threw the following exception:
'Exception occurred with following context:
Compilation: (Project Name)

System.NullReferenceException: Object reference not set to an instance of an object.
   at SecurityCodeScan.Config.ConfigurationReader.GetProjectConfiguration(ImmutableArray`1 additionalFiles, String& path)
   at SecurityCodeScan.Config.ConfigurationManager.GetUpdatedProjectConfiguration(ImmutableArray`1 additionalFiles)
   at SecurityCodeScan.Analyzers.Taint.TaintAnalyzerCSharp.<>c.<Initialize>b__0_0(CompilationStartAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteCompilationStartActions>b__35_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

I'm running Visual Studio 2017 Enterprise Version 15.9.3 on Windows 8.1. My project is .Net 4.7.2 with C# 7.3.
